

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/minervamind}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Toby123$}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql
spring.jpa.defer-datasource-initialization=true
